const $=id=>document.getElementById(id);
const example=$("source");
const checks=[];const compilerVersion="0.2.0";
function lex(src){const out=[];const rx=/\s+|\/\/[^\n]*|"(?:\\.|[^"\\])*"|\d+(?:\.\d+)?(?:u32|f64)?|[a-zA-Z_]\w*|[{}()<>:,;!+=*\/-]/gy;let p=0;while(p<src.length){rx.lastIndex=p;const m=rx.exec(src);if(!m)throw Error("Unexpected token at position "+p);if(!/^\s|^\/\//.test(m[0]))out.push(m[0]);p=rx.lastIndex;}out.push("EOF");return out;}
function parse(tokens){let i=0;const peek=()=>tokens[i],eat=v=>{const t=tokens[i++];if(v&&v!==t)throw Error("Expected "+v+" but got "+t);return t;};
function expr(min=0){let n,t=peek();if(t==="("){eat("(");n=expr();eat(")");}else if(t.startsWith('"')){eat();n={kind:"literal",value:JSON.parse(t),type:"&str"};}else if(/^\d/.test(t)){eat();n={kind:"literal",value:Number(t.replace(/(u32|f64)$/,"")),type:t.includes(".")||t.endsWith("f64")?"f64":"u32"};}else{const name=eat();const macro=peek()==="!";if(macro)eat("!");if(peek()==="("){eat("(");const args=[];while(peek()!==")"){args.push(expr());if(peek()!==",")break;eat(",");}eat(")");n={kind:"call",name,args,macro};}else n={kind:"variable",name};}
const prec={"+":1,"-":1,"*":2,"/":2};while(prec[peek()]!==undefined&&prec[peek()]>=min){const op=eat(),right=expr(prec[op]+1);n={kind:"binary",op,left:n,right};}return n;}
const functions=[];while(peek()!=="EOF"){eat("fn");const name=eat();let generic=null,bound=null;if(peek()==="<"){eat("<");generic=eat();eat(":");bound=eat();eat(">");}eat("(");const params=[];while(peek()!==")"){const param=eat();eat(":");let type=eat();if(type==="&")type+=eat();params.push({name:param,type});if(peek()!==",")break;eat(",");}eat(")");eat("{");const body=[];while(peek()!=="}"){if(peek()==="EOF")throw Error("Unclosed function body");if(peek()==="let"){eat("let");const name=eat();eat("=");const value=expr();eat(";");body.push({kind:"let",name,value});}else{const value=expr();eat(";");body.push({kind:"expression",value});}}eat("}");functions.push({name,generic,bound,params,body});}return functions;}
function analyze(ast){const defs=new Map(ast.map(f=>[f.name,f]));if(defs.size!==ast.length)throw Error("Duplicate function declaration");const instances=new Map(),obligations=[];
function instantiate(name,types){const fn=defs.get(name);if(!fn)throw Error("Undefined function "+name);if(fn.params.length!==types.length)throw Error("Incorrect argument count in "+name);
let genericType=null;for(let i=0;i<types.length;i++){const formal=fn.params[i].type,actual=types[i];if(formal===fn.generic){if(genericType&&genericType!==actual)throw Error("Inconsistent generic arguments");genericType=actual;}else if(formal!==actual)throw Error("Type mismatch: expected "+formal+", got "+actual);}
if(fn.generic){if(fn.bound!=="Display")throw Error("Only Display trait bounds are supported");if(!["u32","f64","&str"].includes(genericType))throw Error("Display not implemented for "+genericType);obligations.push(genericType+": Display");}
const key=name+"<"+(genericType||"")+">";if(instances.has(key))return key;const entry={key,fn,type:genericType};instances.set(key,entry);const env=new Map(fn.params.map((p,i)=>[p.name,types[i]]));
function infer(n){if(n.kind==="literal")return n.type;if(n.kind==="variable"){if(!env.has(n.name))throw Error("Unknown variable "+n.name);return env.get(n.name);}if(n.kind==="binary"){const a=infer(n.left),b=infer(n.right);if(a!==b||!["u32","f64"].includes(a))throw Error("Invalid arithmetic: "+a+" "+n.op+" "+b);return a;}if(n.kind==="call"){if(n.macro){if(n.name!=="println")throw Error("Unsupported macro "+n.name);if(!n.args.length||n.args[0].kind!=="literal"||n.args[0].type!=="&str")throw Error("println! requires a format string");const placeholders=(n.args[0].value.match(/\{\}/g)||[]).length;if(placeholders!==n.args.length-1)throw Error("Format placeholder count mismatch");n.args.slice(1).forEach(infer);return "()";}const ts=n.args.map(infer);n.target=instantiate(n.name,ts);return "()";}throw Error("Unknown expression");}
for(const stmt of fn.body){const ty=infer(stmt.value);if(stmt.kind==="let")env.set(stmt.name,ty);}return key;}
instantiate("main",[]);return {instances:[...instances.values()],obligations};}
function emit(sem){const names=new Map(sem.instances.map((v,i)=>[v.key,"compiled_"+i]));function expression(n){switch(n.kind){case "literal":return JSON.stringify(n.value);case "variable":return n.name;case "binary":return "("+expression(n.left)+n.op+expression(n.right)+")";case "call":return n.macro?"output.push(format("+expression(n.args[0])+",["+n.args.slice(1).map(expression).join(",")+"]))":names.get(n.target)+"("+n.args.map(expression).join(",")+")";}throw Error("Unknown codegen expression");}
let result='"use strict";\nconst output=[];\nconst format=(s,args)=>{let i=0;return s.replace(/\\{\\}/g,()=>String(args[i++]));};\n';for(const inst of sem.instances){result+="function "+names.get(inst.key)+"("+inst.fn.params.map(p=>p.name).join(",")+") { // "+inst.key+"\n";for(const stmt of inst.fn.body)result+=(stmt.kind==="let"?"let "+stmt.name+" = ":"")+expression(stmt.value)+";\n";result+="}\n";}return result+names.get("main<>")+"();\npostMessage(output.join('\\n'));\n";}
let active=0,views=[],timings=[],generated="",worker=null;const labels=["Tokens","AST","Types / generics","Simplified MIR","Generated JavaScript"];
function render(){const tabs=$("tabs");tabs.replaceChildren();labels.forEach((label,i)=>{const b=document.createElement("button");b.textContent=label;b.className=active===i?"active":"";b.onclick=()=>{active=i;render();};tabs.append(b);});$("representation").textContent=active===4?generated:JSON.stringify(views[active],null,2);$("profile").replaceChildren();const total=timings.reduce((a,b)=>a+b.ms,0)||1;for(const t of timings){const row=document.createElement("div");row.className="timing";const name=document.createElement("span");name.textContent=t.name;const bar=document.createElement("div");bar.style.width=(100*t.ms/total)+"%";const value=document.createElement("span");value.textContent=t.ms.toFixed(3)+" ms";row.append(name,bar,value);$("profile").append(row);}}
$("run").onclick=()=>{if(worker){worker.terminate();worker=null;}$("output").textContent="";timings=[];const time=(name,fn)=>{const start=performance.now();const value=fn();timings.push({name,ms:performance.now()-start});return value;};try{const tokens=time("Lex",()=>lex(example.value));const ast=time("Parse",()=>parse(tokens));const sem=time("Analyze",()=>analyze(ast));const mir=time("MIR (illustrative)",()=>sem.instances.map(i=>({function:i.key,blocks:[{name:"bb0",statements:i.fn.body,terminator:"return"}]})));generated=time("Generate JS",()=>emit(sem));views=[tokens,ast,{instances:sem.instances.map(i=>({name:i.fn.name,type:i.type,instance:i.key})),obligations:sem.obligations},mir,generated];render();const url=URL.createObjectURL(new Blob(["onmessage=()=>{\n"+generated+"\n}"],{type:"text/javascript"}));worker=new Worker(url);URL.revokeObjectURL(url);const current=worker;const timeout=setTimeout(()=>{current.terminate();if(worker===current){worker=null;$("output").textContent="Execution timeout";}},1500);current.onmessage=e=>{clearTimeout(timeout);$("output").textContent=e.data;current.terminate();if(worker===current)worker=null;};current.onerror=e=>{clearTimeout(timeout);$("output").textContent="Execution error: "+e.message;current.terminate();if(worker===current)worker=null;};current.postMessage(null);}catch(error){$("output").textContent="Compile error: "+error.message;}};
$("run").click();
