import test from 'node:test';
import assert from 'node:assert/strict';
import {HttpTransport} from '../src/agent/providers/HttpTransport.js';
import {OpenAIProvider} from '../src/agent/providers/OpenAIProvider.js';
import {AnthropicProvider} from '../src/agent/providers/AnthropicProvider.js';
import {GeminiProvider} from '../src/agent/providers/GeminiProvider.js';
import {ProviderRegistry} from '../src/agent/providers/ProviderRegistry.js';
import {ContextManager} from '../src/agent/core/ContextManager.js';
const request={model:'fixture-model',system:'Test',messages:[{role:'user',text:'Task'}],tools:[{name:'workspace_read',description:'Read',inputSchema:{type:'object',properties:{path:{type:'string'}},required:['path']}}]};
function transport(events){let options;return {request:async(url,value)=>{options={url,...value};for(const event of events)value.onEvent(event);return null;},get options(){return options;}};}
test('SSE transport decodes fragmented UTF-8, CRLF, comments and multi-line data',async()=>{const bytes=new TextEncoder().encode(':keepalive\r\nevent: message\r\ndata: {"text":\r\ndata: "Żółć"}\r\n\r\ndata: [DONE]\r\n\r\n');const stream=new ReadableStream({start(controller){for(let i=0;i<bytes.length;i+=3)controller.enqueue(bytes.slice(i,i+3));controller.close();}});let options;const http=new HttpTransport({fetcher:async(url,o)=>{options=o;return new Response(stream,{headers:{'Content-Type':'text/event-stream'}});}}),events=[];assert.equal(await http.request('https://provider.invalid',{headers:{Authorization:'Bearer secret'},onEvent:(value,name)=>events.push({value,name})}),null);assert.deepEqual(events,[{value:{text:'Żółć'},name:'message'}]);assert.equal(options.redirect,'error');});
test('provider HTTP auth errors are not retried, throttling carries bounded Retry-After, errors do not echo bodies',async()=>{for(const [status,retryable]of[[401,false],[429,true],[503,true]]){const http=new HttpTransport({fetcher:async()=>new Response('private-token-reflected',{status,headers:{'Retry-After':'1000'}})});await assert.rejects(http.request('https://provider.invalid'),error=>{assert.equal(error.retryable,retryable);assert.equal(error.retryAfterMs,120000);assert.ok(!error.message.includes('private-token'));return true;});}const http=new HttpTransport({maxBytes:5,fetcher:async()=>new Response('toolargslonger',{headers:{'Content-Type':'text/event-stream'}})});await assert.rejects(http.request('https://provider.invalid'),{code:'PROVIDER_LIMIT'});});
test('OpenAI Responses streams and preserves encrypted reasoning and function-call IDs',async()=>{const output=[{type:'reasoning',id:'reason',summary:[],encrypted_content:'opaque'},{type:'function_call',call_id:'call_1',name:'workspace_read',arguments:'{"path":"src/main.rs"}'}];const wire=transport([{type:'response.output_text.delta',delta:'Inspecting'},{type:'response.completed',response:{status:'completed',output,usage:{input_tokens:50,output_tokens:12,input_tokens_details:{cached_tokens:20}}}}]),provider=new OpenAIProvider({key:'private-test',transport:wire}),delta=[];const result=await provider.complete({...request,onDelta:text=>delta.push(text)});assert.deepEqual(result.calls,[{id:'call_1',name:'workspace_read',arguments:{path:'src/main.rs'}}]);assert.equal(result.usage.cached,20);assert.equal(wire.options.body.store,false);assert.deepEqual(delta,['Inspecting']);const next=provider.input([result,{role:'tool',callId:'call_1',name:'workspace_read',text:'{}'}]);assert.deepEqual(next[0],output[0]);assert.equal(next.at(-1).call_id,'call_1');assert.equal(wire.options.headers.Authorization,'Bearer private-test');});
test('Anthropic reconstructs split arguments, coalesces tool results and retains signed thinking',async()=>{const wire=transport([{type:'message_start',message:{usage:{input_tokens:10,cache_read_input_tokens:4}}},{type:'content_block_start',index:0,content_block:{type:'thinking',thinking:'',signature:''}},{type:'content_block_delta',index:0,delta:{type:'thinking_delta',thinking:'opaque'}},{type:'content_block_delta',index:0,delta:{type:'signature_delta',signature:'signed'}},{type:'content_block_start',index:1,content_block:{type:'tool_use',id:'t1',name:'workspace_read',input:{}}},{type:'content_block_delta',index:1,delta:{type:'input_json_delta',partial_json:'{"path":'}},{type:'content_block_delta',index:1,delta:{type:'input_json_delta',partial_json:'"src/main.rs"}'}},{type:'content_block_stop',index:1},{type:'message_delta',delta:{stop_reason:'tool_use'},usage:{output_tokens:5}},{type:'message_stop'}]);const provider=new AnthropicProvider({key:'key',transport:wire}),result=await provider.complete(request);assert.equal(result.calls[0].arguments.path,'src/main.rs');assert.equal(result.usage.input,14);const next=provider.input([result,{role:'tool',callId:'t1',name:'workspace_read',text:'{}'},{role:'tool',callId:'t2',name:'other',text:'{}',error:true}]);assert.equal(next[0].content[0].signature,'signed');assert.equal(next[1].content.length,2);assert.ok(next[1].content[1].is_error);});
test('Gemini preserves thought signatures and explicit function IDs across tool turns',async()=>{const part={functionCall:{id:'gemini_call',name:'workspace_read',args:{path:'src/main.rs'}},thoughtSignature:'opaque-signature'},wire=transport([{candidates:[{content:{parts:[part]},finishReason:'STOP'}],usageMetadata:{promptTokenCount:20,candidatesTokenCount:7,thoughtsTokenCount:3,cachedContentTokenCount:2}}]),provider=new GeminiProvider({key:'key',transport:wire}),result=await provider.complete(request);assert.equal(result.calls[0].id,'gemini_call');assert.equal(result.usage.output,10);const next=provider.input([result,{role:'tool',callId:'gemini_call',name:'workspace_read',text:'{}'}]);assert.equal(next[0].parts[0].thoughtSignature,'opaque-signature');assert.equal(next[1].parts[0].functionResponse.id,'gemini_call');assert.ok(wire.options.body.tools[0].functionDeclarations[0].parametersJsonSchema);});
test('truncated streams and incomplete outputs never dispatch partial tool calls',async()=>{await assert.rejects(new OpenAIProvider({transport:transport([])}).complete(request),{code:'PROVIDER_STREAM'});await assert.rejects(new AnthropicProvider({transport:transport([{type:'message_delta',delta:{stop_reason:'max_tokens'}},{type:'message_stop'}])}).complete(request),{code:'OUTPUT_LIMIT'});await assert.rejects(new GeminiProvider({transport:transport([{candidates:[{content:{parts:[]},finishReason:'MAX_TOKENS'}]}])}).complete(request),{code:'OUTPUT_LIMIT'});});
test('model catalogs are discovered, API keys verified before connection and redacted after sign out',async()=>{const registry=new ProviderRegistry({environment:{},transport:{request:async()=>({data:[{id:'discovered-model'}]})}});assert.equal(registry.list()[0].connected,false);const connected=await registry.connect('openai','private-memory-key-123');assert.equal(connected.models[0].id,'discovered-model');registry.disconnect('openai');assert.equal(registry.redact('x private-memory-key-123'),'x [REDACTED]');assert.throws(()=>registry.get('openai'),{code:'PROVIDER_NOT_CONNECTED'});await assert.rejects(registry.connect('__proto__','key'),{code:'INVALID_PROVIDER'});});
test('compaction retains pinned constraints and the latest human directive verbatim',async()=>{const session={objective:'Original',latestUser:'Never remove compatibility APIs.',config:{pinnedContext:'Use deterministic tests.'},messages:Array.from({length:12},(_,i)=>({role:i%2?'assistant':'user',text:'message '+i+' '+('x'.repeat(500))})),transcript:[],summary:'',plan:[]};const manager=new ContextManager({contextTokens:8192,outputTokens:1024});await manager.compact(session,{force:true});assert.match(manager.system(session,'system'),/Never remove compatibility APIs\./);assert.match(manager.system(session,'system'),/Use deterministic tests\./);assert.ok(session.compactions);ContextManager.groups(session.messages);});

test('shared tool and approval events remain in the durable audit journal without streaming deltas',async()=>{const {EventLog}=await import('../src/agent/core/EventLog.js'),{SessionEventJournal}=await import('../src/agent/core/SessionEventJournal.js');const events=new EventLog(),session={events:[]},sessions=new Map([['test',session]]),journal=new SessionEventJournal(events,sessions,{maxEvents:3,maxCharacters:10000});events.emit('model.delta',{sessionId:'test',text:'private stream'});events.emit('approval.requested',{sessionId:'test',id:'approval'});events.emit('tool.started',{sessionId:'test',name:'read'});events.emit('tool.completed',{sessionId:'test',result:{text:'source'}});assert.deepEqual(session.events.map(e=>e.type),['approval.requested','tool.started','tool.completed']);events.emit('session.completed',{sessionId:'test'});assert.equal(session.events.length,3);assert.equal(session.events[0].type,'tool.started');journal.close();});
