import test from 'node:test';
import assert from 'node:assert/strict';
import {VtScreen} from '../src/agent/terminal/VtScreen.js';
import {VirtualShell} from '../src/agent/terminal/VirtualShell.js';
import {WorkspaceModel} from '../src/ui/model/WorkspaceModel.js';
import {WorkspaceSynchronizer} from '../src/ui/agent/WorkspaceSynchronizer.js';
import {AgentClient} from '../src/ui/agent/AgentClient.js';
const model=()=>new WorkspaceModel({'Cargo.toml':'[package]\nname="test"\nversion="0.1.0"\n','src/main.rs':'fn main() {}\n','data.txt':'beta\nalpha\nalpha\n'});
test('terminal fragmented controls, SGR, right-margin wrap and truecolor',()=>{const s=new VtScreen(5,3);s.write('12345\x1b[');s.write('31mA');assert.equal(s.text(),'12345\nA\n');assert.equal(s.lines[1][0].fg,1);s.write('\x1b[38:2::10:20:30mB');assert.deepEqual(s.lines[1][1].fg,[10,20,30]);s.write('\r\x1b[2Kdone');assert.equal(s.text(),'12345\ndone\n');});
test('terminal Unicode split surrogates, combining marks and double-width cells',()=>{const s=new VtScreen(10,3);s.write('a\u0301界\ud83d');s.write('\ude80');assert.equal(s.x,5);assert.equal(s.lines[0][0].text,'á');assert.equal(s.lines[0][2].width,0);assert.equal(s.lines[0][3].text,'🚀');assert.equal(s.lines[0][4].width,0);});
test('terminal alternate buffer, bounded scrollback, cursor report and ignored OSC',()=>{const replies=[],s=new VtScreen(10,2,{scrollback:2,onReply:text=>replies.push(text)});s.write('main\x1b[?1049hother\x1b[6n');assert.equal(s.text(),'other\n');assert.deepEqual(replies,['\x1b[1;6R']);s.write('\x1b[?1049l');assert.equal(s.text(),'main\n');s.write('\x1b]52;c;secret\x07\x1b]8;;https://evil.invalid\x1b\\Z');assert.equal(s.text(),'mainZ\n');s.write('\r\n1\r\n2\r\n3\r\n4');assert.equal(s.history.length,2);assert.equal(s.text(),'3\n4');});
test('terminal resizing and keyboard application/control/function modes',()=>{const s=new VtScreen(20,5);s.write('test\x1b[?2004h\x1b[?1h');assert.ok(s.bracketedPaste);assert.ok(s.applicationCursor);s.resize(8,2);assert.equal(s.lines.length,2);assert.ok(s.lines.every(row=>row.length===8));assert.equal(VtScreen.key({key:'c',ctrlKey:true}),'\x03');assert.equal(VtScreen.key({key:'ArrowUp'},true),'\x1bOA');assert.equal(VtScreen.key({key:'ArrowRight',ctrlKey:true}),'\x1b[1;5C');assert.equal(VtScreen.key({key:'V',ctrlKey:true,shiftKey:true}),null);});
test('browser shell pipes, quoting, conditions, source edits and unsupported native commands',async()=>{const m=model(),s=new VirtualShell(m);assert.equal((await s.execute('cat data.txt | sort | uniq')).text,'alpha\nbeta\n');assert.equal((await s.execute('echo "hello world" > hello.txt; cat hello.txt')).text,'hello world\n');assert.equal(m.files['hello.txt'],'hello world\n');assert.equal((await s.execute("false && echo no || echo yes")).text,'yes\n');assert.equal((await s.execute('grep absent data.txt | wc -l')).text,'0\n');assert.equal((await s.execute('cd src; pwd')).text,'/src\n');assert.equal((await s.execute('cargo check')).code,127);assert.equal((await s.execute('echo $(bad)')).code,1);assert.equal((await s.execute('echo "unterminated')).code,1);});
test('browser shell Unicode byte counts, relative paths and file operations',async()=>{const m=model(),s=new VirtualShell(m);await s.execute("echo 'Żółć' > unicode.txt");assert.equal((await s.execute('wc -c unicode.txt')).text,'9\n');await s.execute('cp unicode.txt copy.txt; mv copy.txt moved.txt');assert.equal(m.files['moved.txt'],'Żółć\n');assert.equal(m.files['copy.txt'],undefined);await s.execute('rm moved.txt');assert.equal(m.files['moved.txt'],undefined);assert.equal((await s.execute("printf '%s\\n' a")).text,'a\n');});
function syncFixture(){const m=model();let remote={root:'/workspace',files:{...m.files},hashes:Object.fromEntries(Object.keys(m.files).map(key=>[key,'hash:'+m.files[key]]))};const writes=[];const client={url:'http://127.0.0.1',request:async(path,data)=>{if(!data)return structuredClone(remote);writes.push(data);const changes=[];for(const edit of data.changes){assert.equal(edit.expectedHash,remote.hashes[edit.path]??null);if(edit.text===null){delete remote.files[edit.path];delete remote.hashes[edit.path];}else{remote.files[edit.path]=edit.text;remote.hashes[edit.path]='hash:'+edit.text;}changes.push({path:edit.path,afterHash:remote.hashes[edit.path]??null});}return {changes};}};const sync=new WorkspaceSynchronizer(m,client);return {m,remote,writes,sync,client};}
test('workspace synchronization imports explicitly and reconciles independent edits',async()=>{const f=syncFixture();await f.sync.sync();assert.equal(f.writes.length,0);await f.sync.import();f.m.update('src/main.rs','fn main() { }');f.remote.files['data.txt']='remote\n';f.remote.hashes['data.txt']='hash:remote\n';await f.sync.sync();assert.equal(f.remote.files['src/main.rs'],'fn main() { }');assert.equal(f.m.files['data.txt'],'remote\n');f.sync.disconnect();});
test('divergent edits stop synchronization without overwrites',async()=>{const f=syncFixture();await f.sync.import();f.m.update('data.txt','ours');f.remote.files['data.txt']='theirs';f.remote.hashes['data.txt']='hash:theirs';await assert.rejects(f.sync.sync(),/Sync conflict/);assert.equal(f.m.files['data.txt'],'ours');assert.equal(f.remote.files['data.txt'],'theirs');assert.equal(f.writes.length,0);f.sync.disconnect();});
test('typing during an outgoing write cannot silently consume the incoming common ancestor',async()=>{const f=syncFixture();await f.sync.import();f.m.update('src/main.rs','local source');f.remote.files['data.txt']='remote data';f.remote.hashes['data.txt']='hash:remote data';const request=f.client.request;f.client.request=async(path,data)=>{const value=await request(path,data);if(data)f.m.update('data.txt','typed during IO');return value;};await assert.rejects(f.sync.sync(),/while typing/);assert.equal(f.m.files['data.txt'],'typed during IO');assert.notEqual(f.sync.baseline.files['data.txt'],'remote data');await assert.rejects(f.sync.sync(),/Sync conflict/);f.sync.disconnect();});
test('browser bridge client rejects non-loopback endpoints and does not retain credentials after authentication failure',async()=>{let count=0;const client=new AgentClient({fetcher:async()=>{count++;return new Response(JSON.stringify({error:{message:'Denied'}}),{status:401});}});await assert.rejects(client.connect('https://example.com','private-token-at-least16'),/loopback/);assert.equal(count,0);await assert.rejects(client.connect('http://127.0.0.1:8790','private-token-at-least16'),/Denied/);assert.equal(client.token,null);assert.equal(client.url,null);});
