import test from 'node:test';
import assert from 'node:assert/strict';
import {ToolWindowState, TOOL_SLOTS, TOOL_MODES, DEFAULT_SIZES, clampToolBox} from '../src/ui/docking/ToolWindowState.js';
import {measureToolWindows, toolDropTargets} from '../src/ui/docking/ToolWindowGeometry.js';
const ids = ['project','structure','search','repositories','crates','cargo','problems','debugger','tests','run','terminal','compiler','profile','native-artifacts','language','agent','ui-studio'];
const make = (saved, legacy) => new ToolWindowState(ids, saved, legacy);
const old = () => ({layout:{left:['project','structure','repositories','crates','cargo'],right:['compiler','profile','native-artifacts','language','agent','ui-studio'],bottom:['run','terminal','search','problems','debugger','tests']},active:{left:'project',right:'compiler',bottom:'run'},sizes:{left:245,right:560,bottom:235},hidden:[],collapsedRegions:[]});
function invariant(model) {
  const s=model.value, owned=TOOL_SLOTS.flatMap(slot=>s.slots[slot].order);
  assert.equal(owned.length, model.ids.size);assert.equal(new Set(owned).size,model.ids.size);
  for(const slot of TOOL_SLOTS){const {order,active}=s.slots[slot];assert.ok(active===null||order.includes(active));if(active)assert.notEqual(s.windows[active].mode,'floating');for(const id of order)assert.equal(s.windows[id].anchor,slot);}
  for(const id of model.ids){const w=s.windows[id];assert.ok(TOOL_MODES.includes(w.mode));assert.ok(!w.open||w.mode==='floating');}
  assert.deepEqual(new ToolWindowState(model.ids,model.snapshot()).snapshot(),model.snapshot());
}
function inBounds(rect,w,h) {for(const k of ['x','y','width','height'])assert.ok(Number.isFinite(rect[k]),JSON.stringify(rect));assert.ok(rect.x>=-1e-8&&rect.y>=-1e-8&&rect.width>=0&&rect.height>=0,JSON.stringify(rect));assert.ok(rect.x+rect.width<=w+1e-6&&rect.y+rect.height<=h+1e-6,`${JSON.stringify(rect)} outside ${w}x${h}`);}

test('editor-first defaults register every tool once and open only Project and Cargo',()=>{const m=make();invariant(m);assert.deepEqual(ids.filter(id=>m.visible(id)),['project','cargo']);assert.deepEqual(m.value.sizes,DEFAULT_SIZES);assert.equal(m.value.slots['bottom-left'].active,null);});
test('one active tool per slot; hide does not reveal an unrelated neighbour',()=>{const m=make();m.open('compiler');assert.equal(m.visible('cargo'),false);m.hide('compiler');assert.equal(m.value.slots['right-top'].active,null);m.open('cargo');m.open('agent');assert.ok(m.visible('cargo')&&m.visible('agent'));});
test('all six anchors and ordered sidebar insertion are first-class positions',()=>{const m=make();for(const slot of TOOL_SLOTS){m.move('compiler',slot);assert.equal(m.value.windows.compiler.anchor,slot);assert.equal(m.value.slots[slot].active,'compiler');invariant(m);}m.move('compiler','left-top','project');assert.deepEqual(m.value.slots['left-top'].order,['compiler','project','repositories']);const before=m.snapshot();m.move('compiler','left-top','compiler');assert.deepEqual(m.snapshot(),before);});
test('invalid commands are atomic, never remove an existing owner',()=>{const m=make(),before=m.snapshot();for(const f of [()=>m.move('compiler','top'),()=>m.move('compiler','left-top','run'),()=>m.move('no-tool','right-top'),()=>m.setMode('compiler','os-window'),()=>m.setSize('left',NaN),()=>m.setSize('top',200),()=>m.setSplit('right',Infinity)]){assert.throws(f);assert.deepEqual(m.snapshot(),before);}});
test('floating tools retain homes, geometry, visibility and independent lifetime',()=>{const m=make();m.setBox('compiler',{x:20,y:30,width:780,height:510});m.setMode('compiler','floating');m.open('cargo');assert.ok(m.visible('compiler')&&m.visible('cargo'));m.hide('compiler');assert.equal(m.visible('compiler'),false);m.open('compiler');assert.equal(m.value.windows.compiler.box.width,780);m.setMode('compiler','docked');assert.equal(m.visible('cargo'),false);assert.equal(m.value.windows.compiler.anchor,'right-top');invariant(m);});
test('four view modes round-trip, sidebar removal hides but registration remains',()=>{const m=make();for(const mode of TOOL_MODES){m.setMode('compiler',mode);invariant(m);}m.setSidebar('compiler',false);assert.equal(m.visible('compiler'),false);assert.equal(m.value.windows.compiler.sidebar,false);m.open('compiler');assert.equal(m.value.windows.compiler.sidebar,true);});
test('hide all restores selected tools and floating windows without replacing their modes',()=>{const m=make();m.open('terminal');m.open('agent');m.setMode('compiler','floating');const before=m.snapshot();m.toggleAll();assert.ok(ids.every(id=>!m.visible(id)));m.toggleAll();assert.deepEqual(m.snapshot(),before);});
test('collapse targets both docked slots on one side, not another side or floats',()=>{const m=make();m.open('structure');m.setMode('compiler','floating');m.collapse('left');assert.equal(m.visible('project'),false);assert.equal(m.visible('structure'),false);assert.ok(m.visible('cargo')&&m.visible('compiler'));});
test('sizes and splits are bounded and snapshots cannot mutate live state',()=>{const m=make();m.setSize('left',-200);m.setSize('right',1e9);m.setSplit('left',-1);m.setSplit('right',2);assert.deepEqual([m.value.sizes.left,m.value.sizes.right,m.value.splits.left,m.value.splits.right],[180,1600,.15,.85]);const copy=m.snapshot();copy.slots['left-top'].order.length=0;invariant(m);});
test('untouched laboratory v3 default migrates to RustRover-style default',()=>{assert.deepEqual(make(null,old()).snapshot(),make().snapshot());});
test('custom v3 placements, sizes, hidden state and collapsed regions survive migration',()=>{const legacy=old();legacy.layout.right=legacy.layout.right.filter(id=>id!=='compiler');legacy.layout.bottom.unshift('compiler');legacy.active.bottom='compiler';legacy.sizes.right=430;legacy.hidden=['project'];legacy.collapsedRegions=['right'];const m=make(null,legacy);assert.equal(m.value.windows.compiler.anchor,'bottom-left');assert.equal(m.value.slots['bottom-left'].active,'compiler');assert.equal(m.value.slots['right-top'].active,null);assert.equal(m.value.sizes.right,430);assert.notEqual(m.value.slots['left-top'].active,'project');invariant(m);});
test('malformed persistence restores atomically; unknown plugins are removed and new ones added',()=>{for(const mutate of [s=>s.version=80,s=>s.slots['left-top'].order.push('project'),s=>delete s.slots['right-top'],s=>s.windows.project.anchor='bottom-left',s=>s.windows.project.mode='unknown']){const saved=make().snapshot();mutate(saved);assert.deepEqual(make(saved).snapshot(),make().snapshot());}const prior=make();prior.move('compiler','left-bottom');const m=new ToolWindowState([...ids.filter(id=>id!=='crates'),'new-plugin'],prior.snapshot());assert.equal(m.value.windows.compiler.anchor,'left-bottom');assert.equal(m.value.windows['new-plugin'].anchor,'right-top');assert.equal(m.visible('new-plugin'),false);invariant(m);});
test('non-finite persisted geometry gets safe defaults; snapshot input is never modified',()=>{const s=make().snapshot();s.sizes.left=NaN;s.splits.right=Infinity;s.windows.project.box={x:NaN,y:-1e8,width:1e8,height:-100};const before=structuredClone(s),m=make(s);assert.deepEqual(s,before);assert.equal(m.value.sizes.left,256);assert.equal(m.value.splits.right,.5);assert.deepEqual(m.value.windows.project.box,{x:80,y:-10000,width:4000,height:160});});
test('ten thousand deterministic edits maintain ownership and lossless round trips',()=>{const m=make();let seed=123456;const next=n=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed%n;};for(let i=0;i<10000;i++){const id=ids[next(ids.length)],n=next(6);if(n===0)m.move(id,TOOL_SLOTS[next(6)]);else if(n===1)m.setMode(id,TOOL_MODES[next(4)]);else if(n===2)m.hide(id);else if(n===3)m.open(id);else if(n===4)m.toggleAll();else m.setSidebar(id,!!next(2));invariant(m);}});
test('bottom tools span the workbench by default and the center in wide screen layout',()=>{const m=make();m.open('run');let g=measureToolWindows(m.value,1500,900);assert.equal(g.regions.bottom.width,1500);assert.equal(g.regions.left.height,649);m.value.wide=true;g=measureToolWindows(m.value,1500,900);assert.equal(g.regions.left.height,900);assert.equal(g.regions.bottom.width,g.editor.width);assert.equal(g.regions.bottom.x,g.editor.x);});
test('each edge supports two simultaneously visible panels with a real split divider',()=>{const m=make();m.open('structure');m.open('agent');m.open('run');m.open('search');m.setSplit('bottom',.65);const g=measureToolWindows(m.value,1500,900);assert.equal(g.panels.length,6);assert.equal(g.dividers.filter(d=>d.kind==='split').length,3);assert.ok(g.slotRects['bottom-left'].width>g.slotRects['bottom-right'].width);for(const p of g.panels)inBounds(p.rect,1500,900);});
test('sliding tools overlay without reserving editor space; dock-unpinned reserves until hidden',()=>{const m=make();m.setMode('compiler','sliding');const g=measureToolWindows(m.value,1500,900);assert.equal(g.regions.right.width,0);assert.ok(g.panels.find(p=>p.id==='compiler').overlay);m.setMode('compiler','unpinned');assert.equal(measureToolWindows(m.value,1500,900).regions.right.width,304);});
test('narrow screens present only explicitly requested sidebar overlays without mutating state',()=>{const m=make(),before=m.snapshot();let g=measureToolWindows(m.value,320,700);assert.equal(g.panels.length,0);assert.equal(g.editor.width,320);g=measureToolWindows(m.value,320,700,{overlay:'cargo'});assert.equal(g.panels.length,1);assert.equal(g.panels[0].id,'cargo');assert.ok(g.panels[0].overlay);assert.deepEqual(m.snapshot(),before);assert.equal(measureToolWindows(m.value,1500,900).panels.length,2);});
test('maximization is presentation-only and restores preferred edge geometry',()=>{const m=make(),before=m.snapshot(),normal=measureToolWindows(m.value,1500,900);const full=measureToolWindows(m.value,1500,900,{maximized:'project'});assert.equal(full.panels.length,1);assert.deepEqual(full.panels[0].rect,{x:0,y:0,width:1500,height:900});assert.equal(full.dividers.length,0);assert.deepEqual(m.snapshot(),before);assert.deepEqual(measureToolWindows(m.value,1500,900),normal);});
test('geometry remains finite and in bounds at small and large viewport sizes',()=>{const m=make();m.open('run');m.open('search');m.open('structure');m.open('agent');for(const wide of [false,true])for(const width of [0,1,16,160,320,600,999,1000,1920,5000])for(const height of [0,1,50,160,400,1000]){m.value.wide=wide;const g=measureToolWindows(m.value,width,height,{overlay:'cargo'});inBounds(g.editor,width,height);for(const p of g.panels)inBounds(p.rect,width,height);}});
test('floating viewport clamps never overwrite desktop rectangles',()=>{const box={x:1600,y:900,width:900,height:600},copy={...box};for(const [w,h] of [[320,640],[1920,1080],[1,1]])inBounds(clampToolBox(box,w,h),w,h);assert.deepEqual(box,copy);});
test('drag guides expose exactly six bounded, named anchor targets',()=>{for(const [w,h] of [[320,500],[1500,900],[0,0]]){const targets=toolDropTargets(w,h);assert.deepEqual(targets.map(t=>t.slot),TOOL_SLOTS);for(const rect of targets)inBounds(rect,w,h);}});
