import {Dom} from './Dom.js';
import {SpanRegistry} from './SpanRegistry.js';
export class DebuggerView {
  constructor(root,selection,onCommand){this.root=root;this.registry=new SpanRegistry(selection,'debugger');this.frame=0;this.toolbar=Dom.element('div','debug-toolbar');for(const [label,command,icon] of [['Resume','continue','run'],['Pause','pause','pause'],['Step instruction','step','step'],['Step line','step-line','line'],['Back instruction','back','step'],['Back line','back-line','line']])this.toolbar.append(Dom.button(label,()=>onCommand(command),{icon}));this.body=Dom.element('div','debug-body');root.append(this.toolbar,this.body);this.render(null);}
  render(state){this.state=state;this.registry.clear();this.body.replaceChildren();for(const button of this.toolbar.querySelectorAll('button'))button.disabled=!state||state.done;if(!state){Dom.empty(this.body,'Debug runs the executable MIR. Start Debug to inspect real call frames and registers.');return;}
    const summary=Dom.element('div','debug-summary',`${state.done?'Finished':'Paused'} · ${state.steps.toLocaleString()} instructions`);this.body.append(summary);const split=Dom.element('div','debug-split'),frames=Dom.element('div','stack-frames'),locals=Dom.element('div','stack-locals');split.append(frames,locals);this.body.append(split);
    this.frame=Math.min(this.frame,Math.max(0,state.frames.length-1));const displayed=[...state.frames].reverse();displayed.forEach((frame,index)=>{const button=Dom.button(`${frame.function} / ${frame.block}`,()=>{this.frame=index;this.render(state);},{icon:'code',className:'stack-frame'});button.classList.toggle('active',index===this.frame);frames.append(button);});
    const frame=displayed[this.frame];if(frame){const table=Dom.element('table','data-table');for(const local of frame.locals){const row=Dom.element('tr');row.append(Dom.element('td','',`${local.name} · %${local.slot}`),Dom.element('td','',local.type),Dom.element('td','',local.value));this.registry.bind(row,local.span);table.append(row);}locals.append(table);}else locals.append(Dom.element('p','view-note',state.result===null?'Program returned unit.':String(state.result)));
  }
}
