import {SpanRegistry} from './SpanRegistry.js';
import {Dom} from './Dom.js';
export class ProfileView {
  constructor(root,selection){this.root=root;this.registry=selection?new SpanRegistry(selection,'parallel-profile'):null;}
  invalidate(){this.registry?.clear();this.root.replaceChildren(Dom.element('p','view-note','Source or build settings changed. Compile again to refresh timing and source mappings.'));}
  native(result){
    this.registry?.clear();this.root.replaceChildren();const summary=result.buildSummary;
    this.root.append(Dom.element('h3','section-heading','Native Cargo build'),Dom.element('p','view-note',`${summary.jobs} Cargo jobs · ${summary.fresh} fresh artifacts · ${summary.rebuilt} rebuilt artifacts · ${summary.elapsedMs.toFixed(2)} ms process wall time`),Dom.element('p','view-note','Cargo schedules its actual dependency graph. Artifact messages do not prove simultaneous CPU activity; see the Cargo timing report for measured concurrency.'));
    if(result.timingReport?.html){const frame=Dom.element('iframe','cargo-timing-frame');frame.title='Cargo build timing report';frame.setAttribute('sandbox','allow-scripts');frame.srcdoc="<meta http-equiv=\"Content-Security-Policy\" content=\"default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'\">"+result.timingReport.html;this.root.append(frame);}
    else this.root.append(Dom.element('p','view-note',result.timingReport?.omitted??'Enable Generate Cargo timing report before building to inspect actual crate timings.'));
  }
  parallel(report){
    const panel=Dom.element('section','parallel-profile');panel.append(Dom.element('h3','section-heading','Parallel parser tasks'),Dom.element('p','view-note',`${report.usedWorkers} workers · ${report.peakActiveTasks} overlapping tasks · ${report.wallMs.toFixed(2)} ms pool wall time · ${report.taskMs.toFixed(2)} ms summed worker lex/parse time`));
    if(report.fallbackReason)panel.append(Dom.element('p','warning-note','Serial fallback: '+report.fallbackReason));
    for(const task of report.tasks){const row=Dom.element('div','timing-row'),label=Dom.element('div','timing-label');label.append(Dom.element('span','',`Worker ${task.lane+1} · ${task.file}`),Dom.element('code','',`${(task.endMs-task.startMs).toFixed(2)} ms`));const track=Dom.element('div','timing-track'),bar=Dom.element('div','timing-fill');bar.style.marginLeft=(task.startMs/(report.wallMs||1)*100)+'%';bar.style.width=Math.max(.1,(task.endMs-task.startMs)/(report.wallMs||1)*100)+'%';track.append(bar);row.append(label,track);panel.append(row);this.registry?.bind(row,task.span);}
    panel.append(Dom.element('p','view-note','Timelines measure dispatched task round trips, including startup and transfer. Summed worker times are not additive pipeline wall time. Shared semantic state and final verification remain sequential.'));this.root.append(panel);
  }
  render(build){this.registry?.clear();this.root.replaceChildren();const hero=Dom.element('div','profile-hero');hero.append(Dom.element('span','metric-value',build.elapsedMs.toFixed(2)),Dom.element('span','metric-unit','ms project compile'),Dom.element('span','cache-badge',build.cacheHit?'EXACT CACHE HIT':`${build.cache.parsedFiles} parsed · ${build.cache.reusedFiles} reused`));this.root.append(hero);
    const total=build.timings.reduce((n,t)=>n+t.ms,0)||1;for(const pass of build.timings){const row=Dom.element('div','timing-row'),label=Dom.element('div','timing-label');label.append(Dom.element('span','',pass.name),Dom.element('code','',pass.ms.toFixed(3)+' ms'));const track=Dom.element('div','timing-track'),fill=Dom.element('div','timing-fill');fill.style.width=Math.max(.5,pass.ms/total*100)+'%';track.append(fill);row.append(label,track);this.root.append(row);}this.root.append(Dom.element('p','view-note',build.cacheHit?'No compiler passes reran. This is an exact-project result cache hit, not a new measurement of those passes.':'Wall-clock measurements inside the compiler worker. Parsing can reuse unchanged files; unchanged typed queries may also be reused. Parallel lex/parse rows are summed worker durations, not additive project wall time.'));
    if(build.parallel)this.parallel(build.parallel);
    const counts=Dom.element('div','profile-counts');for(const [label,value] of [['Tokens',build.tokens.length],['Instances',build.sem.instances.length],['MIR blocks',build.mir.reduce((n,fn)=>n+fn.blocks.length,0)],['Optimizations',build.optimizations.length]]){const card=Dom.element('div');card.append(Dom.element('strong','',value),Dom.element('span','',label));counts.append(card);}this.root.append(counts);
  }
}
