import {Dom} from '../views/Dom.js';

/** Presentation only: live transcript, approvals, tool audit, context and capability explorer. */
export class AgentView {
  constructor(root, actions) {
    this.root=root;this.actions=actions;this.session=null;this.stream=null;this.callCards=new Map();this.approvalCards=new Map();this.trace=[];root.classList.add('agent-workbench');
    const heading=Dom.element('div','agent-heading');heading.append(Dom.element('strong','','Ferrite Agent'),this.badge=Dom.element('span','agent-badge','Disconnected'),Dom.button('Connect',()=>actions.connect()),Dom.button('Disconnect',()=>actions.disconnect()));
    const selectors=Dom.element('div','agent-selectors');this.provider=this.select('Agent provider',[['openai','OpenAI'],['anthropic','Anthropic'],['gemini','Google Gemini']]);this.provider.id='agent-provider';this.provider.onchange=()=>this.showModels();
    this.model=Dom.element('input');this.model.id='agent-model';this.model.placeholder='Connect API → discover models';this.model.setAttribute('aria-label','Agent model');this.model.setAttribute('list','agent-models');this.modelList=Dom.element('datalist');this.modelList.id='agent-models';
    this.mode=this.select('Agent approval mode',[['ask','Ask before edits / execution'],['auto-edit','Auto edits · ask execution'],['read-only','Read-only analysis'],['trusted','Full host access · trusted']]);this.mode.id='agent-mode';this.mode.onchange=()=>{if(this.mode.value==='trusted'&&!confirm('Full host access permits this coding agent to execute arbitrary native commands without per-command approval. It is NOT sandboxed. Trust only code and tasks you understand. Enable for this session?'))this.mode.value='ask';};
    selectors.append(this.provider,this.model,this.modelList,this.mode);
    const accounts=Dom.element('div','agent-toolbar');accounts.append(Dom.button('API sign in',()=>actions.apiLogin()),Dom.button('Models',()=>actions.models()),Dom.button('API sign out',()=>actions.apiLogout()),Dom.button('Import native workspace',()=>actions.importWorkspace()));
    this.workspaceStatus=Dom.element('div','agent-workspace-status','Agent bridge operates on its selected native checkout. Browser workspace sync is off until explicitly imported.');
    const sessions=Dom.element('div','agent-toolbar');this.sessionSelect=this.select('Agent session',[]);this.sessionSelect.id='agent-session-select';this.sessionSelect.onchange=()=>actions.loadSession(this.sessionSelect.value);sessions.append(this.sessionSelect,Dom.button('New',()=>actions.newSession()),Dom.button('Fork',()=>actions.fork()),Dom.button('Export',()=>actions.exportSession()));
    const tabs=Dom.element('div','agent-tabs');this.views=new Map();this.tabButtons=new Map();
    for(const [id,title] of [['chat','Conversation'],['trace','Execution trace'],['context','Context'],['tools','MCP / tools']]){const button=Dom.button(title,()=>this.tab(id));button.dataset.agentTab=id;tabs.append(button);this.tabButtons.set(id,button);const body=Dom.element('div','agent-tab-content');body.dataset.agentContent=id;body.hidden=id!=='chat';this.views.set(id,body);}
    this.approvals=Dom.element('div','agent-approvals');this.approvals.setAttribute('aria-live','polite');this.chat=Dom.element('div','agent-chat');this.chat.id='agent-chat';this.chat.setAttribute('role','log');this.views.get('chat').append(this.approvals,this.chat);
    this.chat.append(Dom.element('div','agent-empty','Connect the trusted local bridge, sign in with a provider API key, choose a model, and enter a task. Tool approvals, diffs, plans and actual results appear here.'));
    this.plan=Dom.element('div','agent-plan');this.metrics=Dom.element('div','agent-metrics','No session');this.traceList=Dom.element('div','agent-trace');this.views.get('trace').append(this.plan,this.metrics,this.traceList);
    const settings=Dom.element('div','agent-context-settings');this.contextInput=this.number('Context budget (estimated tokens)',32768,8192,2000000);this.outputInput=this.number('Output reserve',4096,256,32768);this.stepsInput=this.number('Max model turns per run',40,1,200);this.budgetInput=this.number('Session token budget',500000,1000,10000000);
    for(const field of [this.contextInput,this.outputInput,this.stepsInput,this.budgetInput])settings.append(field.label);
    this.compactCheckbox=Dom.element('input');this.compactCheckbox.type='checkbox';this.compactCheckbox.checked=true;const compactLabel=Dom.element('label','agent-checkbox');compactLabel.append(this.compactCheckbox,document.createTextNode('Use model-assisted context summaries (additional API usage)'));settings.append(compactLabel,Dom.button('Compact now',()=>actions.compact()));
    this.pinned=Dom.element('textarea');this.pinned.rows=4;this.pinned.maxLength=16000;this.pinned.placeholder='Pinned constraints retained verbatim across compaction';this.pinned.setAttribute('aria-label','Pinned context');settings.append(this.pinned);
    this.contextMeter=Dom.element('progress');this.contextMeter.max=1;this.contextMeter.value=0;this.contextDescription=Dom.element('div','agent-note','Context usage is an estimate, not a provider tokenizer. Summaries are lossy; full transcripts and tool artifacts remain on the bridge.');this.summary=Dom.element('pre','agent-json');this.summary.textContent='No compacted history.';this.views.get('context').append(settings,this.contextMeter,this.contextDescription,this.summary);
    this.toolsSearch=Dom.element('input');this.toolsSearch.placeholder='Filter tools or capabilities';this.toolsSearch.setAttribute('aria-label','Filter MCP tools');this.toolsSearch.oninput=()=>this.renderTools();this.toolList=Dom.element('div','agent-tool-list');this.mcpConfig=Dom.element('pre','agent-json');this.views.get('tools').append(this.toolsSearch,this.mcpConfig,this.toolList);
    this.error=Dom.element('div','agent-error');this.error.setAttribute('role','alert');this.error.hidden=true;
    this.prompt=Dom.element('textarea');this.prompt.id='agent-prompt';this.prompt.rows=3;this.prompt.placeholder='Describe a coding task. Source and terminal output are treated as untrusted context.';this.prompt.setAttribute('aria-label','Coding agent prompt');this.prompt.onkeydown=event=>{if((event.ctrlKey||event.metaKey)&&event.key==='Enter'){event.preventDefault();actions.run();}};
    const composer=Dom.element('div','agent-composer'),commands=Dom.element('div','agent-toolbar');this.runButton=Dom.button('Run task',()=>actions.run());this.runButton.id='agent-run';this.runButton.classList.add('agent-primary');this.resumeButton=Dom.button('Resume',()=>actions.resume());this.stopButton=Dom.button('Stop',()=>actions.stop());this.stopButton.id='agent-stop';commands.append(this.runButton,this.resumeButton,this.stopButton,Dom.element('span','agent-shortcut','Ctrl/Cmd+Enter'));composer.append(this.prompt,commands);
    root.append(heading,selectors,accounts,this.workspaceStatus,sessions,tabs,...this.views.values(),this.error,composer);this.providers=[];this.tools=[];this.tab('chat');this.connected(false);
  }
  select(label,options){const select=Dom.element('select');select.setAttribute('aria-label',label);for(const [value,title] of options){const option=Dom.element('option','',title);option.value=value;select.append(option);}return select;}
  number(title,value,min,max){const label=Dom.element('label','agent-field'),input=Dom.element('input');input.type='number';input.min=min;input.max=max;input.value=value;input.setAttribute('aria-label',title);label.append(Dom.element('span','',title),input);return {label,input};}
  tab(id){for(const [key,view] of this.views)view.hidden=key!==id;for(const [key,button] of this.tabButtons){button.classList.toggle('active',key===id);button.setAttribute('aria-selected',String(key===id));}}
  config(){return {provider:this.provider.value,model:this.model.value.trim(),mode:this.mode.value,contextTokens:Number(this.contextInput.input.value),outputTokens:Number(this.outputInput.input.value),maxSteps:Number(this.stepsInput.input.value),maxTotalTokens:Number(this.budgetInput.input.value),modelCompaction:this.compactCheckbox.checked,pinnedContext:this.pinned.value};}
  connected(value,capabilities){this.isConnected=value;this.badge.textContent=value?'Connected · trusted host':'Disconnected';this.badge.classList.toggle('connected',value);this.runButton.disabled=!value;this.resumeButton.disabled=!value;this.stopButton.disabled=!value;if(capabilities){this.providers=capabilities.providers;this.tools=capabilities.tools;this.showModels();this.renderTools();this.mcpConfig.textContent='MCP endpoint: '+this.actions.bridgeUrl()+'/mcp\nProtocols: '+capabilities.mcpVersions.join(', ')+'\nClaude / Gemini JSON configuration (Codex TOML: docs/agent-workbench.md):\n'+JSON.stringify({mcpServers:{ferrite:{command:'node',args:['/absolute/path/to/Ferrite/tools/agent-mcp.mjs','--bridge',this.actions.bridgeUrl()],env:{FERRITE_AGENT_TOKEN:'<bridge token — configure privately>'}}}},null,2);}}
  showModels(){const provider=this.providers.find(p=>p.id===this.provider.value);this.modelList.replaceChildren();for(const model of provider?.models??[]){const option=Dom.element('option','',model.name);option.value=model.id;this.modelList.append(option);}this.model.placeholder=provider?.connected?'Select a tool-capable model from the API catalog':'API sign in required';}
  setSessions(sessions){const selected=this.session?.id;this.sessionSelect.replaceChildren();const blank=Dom.element('option','','New session');blank.value='';this.sessionSelect.append(blank);for(const session of sessions){const option=Dom.element('option','',`${session.status} · ${session.objective||session.id.slice(0,8)}`);option.value=session.id;this.sessionSelect.append(option);}this.sessionSelect.value=selected??'';}
  setSession(session){
    this.session=session;this.stream=null;this.chat.replaceChildren();this.callCards.clear();this.trace=[];this.traceList.replaceChildren();
    if(!session){this.chat.append(Dom.element('div','agent-empty','Enter a task to start a new session.'));return;}
    this.provider.value=session.config.provider;this.showModels();this.model.value=session.config.model;this.mode.value=session.config.mode;this.contextInput.input.value=session.config.contextTokens;this.outputInput.input.value=session.config.outputTokens;this.stepsInput.input.value=session.config.maxSteps;this.budgetInput.input.value=session.config.maxTotalTokens;this.compactCheckbox.checked=session.config.modelCompaction;this.pinned.value=session.config.pinnedContext??'';
    for(const message of session.transcript.slice(-300)){if(message.role==='user')this.message('You',message.text);else if(message.role==='assistant'){this.message('Agent',message.text);for(const call of message.calls??[])this.toolStarted(call.id,call.name,call.arguments);}else if(message.role==='tool'){let result;try{result=JSON.parse(message.text);}catch{result=message.text;}this.toolFinished(message.callId,result,message.error);}}
    for(const event of (session.events??[]).slice(-150))this.audit(event);this.renderPlan(session.plan);this.summary.textContent=session.summary||'No compacted history.';this.status(session.status);this.usage(session.usage);this.scroll();
  }
  status(status){if(this.session)this.session.status=status;this.badge.textContent=this.isConnected?status:'Disconnected';const active=['running','compacting','waiting'].includes(status);this.runButton.disabled=!this.isConnected||active;this.resumeButton.disabled=!this.isConnected||active;this.stopButton.disabled=!this.isConnected||!active;this.prompt.disabled=active;}
  message(role,text){if(!text)return null;this.chat.querySelector('.agent-empty')?.remove();const card=Dom.element('article','agent-message '+(role==='You'?'agent-user':'agent-assistant'));card.append(Dom.element('div','agent-message-title',role));const content=Dom.element('div','agent-message-text',String(text).slice(0,100000));card.append(content);this.chat.append(card);this.limitChat();return {card,content};}
  limitChat(){while(this.chat.children.length>300)this.chat.firstElementChild.remove();}
  toolStarted(id,name,args){if(this.callCards.has(id))return;const card=Dom.element('details','agent-tool-call');card.dataset.callId=id;const title=Dom.element('summary','',name+' · running'),input=Dom.element('pre','agent-json',JSON.stringify(args,null,2).slice(0,12000)),result=Dom.element('pre','agent-json');card.append(title,input,result);this.chat.append(card);this.callCards.set(id,{card,title,result,name});this.limitChat();}
  toolFinished(id,value,error=false){const item=this.callCards.get(id);if(!item)return;item.title.textContent=item.name+(error?' · failed':' · complete');item.card.classList.toggle('failed',error);item.result.textContent=JSON.stringify(value,null,2).slice(0,24000);if(value?.artifact){const button=Dom.button('Read full artifact',()=>this.actions.artifact(value.artifact));item.card.append(button);}}
  renderPlan(steps=[]){this.plan.replaceChildren();for(const step of steps){const row=Dom.element('div','agent-plan-step '+step.status);row.append(Dom.element('span','',step.status==='completed'?'✓':step.status==='in_progress'?'◉':'○'),Dom.element('span','',step.step));this.plan.append(row);}}
  usage(usage){this.metrics.textContent=`Input ${Number(usage?.input??0).toLocaleString()} · Output ${Number(usage?.output??0).toLocaleString()} · Cached ${Number(usage?.cached??0).toLocaleString()} · Compactions ${this.session?.compactions??0}`;}
  audit(event){if(event.type==='model.delta')return;this.trace.push(event);if(this.trace.length>200)this.trace.shift();const row=Dom.element('details','agent-trace-event'),title=Dom.element('summary','',`${event.at?.slice(11,19)??''}  ${event.type}${event.name?' · '+event.name:''}`);row.append(title,Dom.element('pre','agent-json',JSON.stringify(event,null,2).slice(0,16000)));this.traceList.append(row);while(this.traceList.children.length>200)this.traceList.firstElementChild.remove();}
  approval(request){
    if(this.approvalCards.has(request.id))return;const card=Dom.element('section','agent-approval');card.dataset.approvalId=request.id;card.append(Dom.element('strong','',`${request.tool} · ${request.risk} approval`),Dom.element('div','agent-note',request.sessionId===this.session?.id?'Current agent session':'External MCP / another session'),Dom.element('pre','agent-json',JSON.stringify(request.arguments,null,2).slice(0,12000)));
    for(const edit of Array.isArray(request.preview)?request.preview:[]){const details=Dom.element('details','agent-diff');details.append(Dom.element('summary','',edit.path),Dom.element('pre','agent-diff-before','− BEFORE\n'+String(edit.before??'(new file)').slice(0,14000)),Dom.element('pre','agent-diff-after','+ AFTER\n'+String(edit.after??'(deleted)').slice(0,14000)));card.append(details);}
    const controls=Dom.element('div','agent-toolbar');controls.append(Dom.button('Approve once',()=>this.actions.approve(request.id,true)),Dom.button('Deny',()=>this.actions.approve(request.id,false)));card.append(controls);this.approvals.append(card);this.approvalCards.set(request.id,card);this.tab('chat');
  }
  handle(event){
    if(event.type==='approval.requested'){this.approval(event);return;}
    if(event.type==='approval.resolved'){this.approvalCards.get(event.id)?.remove();this.approvalCards.delete(event.id);}
    if(event.sessionId!==this.session?.id)return;
    this.audit(event);
    switch(event.type){
      case 'session.started':this.status('running');break;
      case 'message.user':this.message('You',event.text);break;
      case 'model.started':if(this.stream)this.stream.card.remove();this.stream=null;break;
      case 'model.delta':if(!this.stream)this.stream=this.message('Agent',' ');if(this.stream.content.textContent.length<100000)this.stream.content.append(document.createTextNode(event.text));break;
      case 'message.assistant':if(this.stream){this.stream.content.textContent=event.text;this.stream=null;}else this.message('Agent',event.text);for(const call of event.calls??[])this.toolStarted(call.id,call.name,call.arguments);break;
      case 'tool.started':this.toolStarted(event.callId,event.name,event.arguments);break;
      case 'tool.completed':this.toolFinished(event.callId,event.result);break;
      case 'tool.failed':this.toolFinished(event.callId,event.error,true);break;
      case 'plan.updated':this.renderPlan(event.steps);break;
      case 'usage.updated':this.session.usage=event.usage;this.usage(event.usage);break;
      case 'context.measured':this.contextMeter.value=event.estimatedTokens/event.capacity;this.contextDescription.textContent=`Estimated context: ${event.estimatedTokens.toLocaleString()} / ${event.capacity.toLocaleString()} tokens, including output reserve. Complete tool groups are retained; compaction is lossy.`;break;
      case 'context.compacted':this.session.compactions=event.count;this.usage(this.session.usage);break;
      case 'session.completed':this.status('completed');break;
      case 'session.paused':this.status('paused');break;
      case 'session.cancelled':this.status('cancelled');break;
      case 'session.failed':this.status('failed');this.showError(event.error.message);break;
    }this.scroll();
  }
  scroll(){const pane=this.views.get('chat');if(pane.scrollTop+pane.clientHeight>=pane.scrollHeight-350)pane.scrollTop=pane.scrollHeight;}
  showError(error){this.error.hidden=!error;this.error.textContent=error?.message??error??'';}
  renderTools(){
    const query=this.toolsSearch.value.toLowerCase();this.toolList.replaceChildren();
    for(const tool of this.tools.filter(tool=>(tool.name+' '+tool.description+' '+tool.category).toLowerCase().includes(query))){const card=Dom.element('details','agent-tool-definition');card.append(Dom.element('summary','',`${tool.name} · ${tool.risk}`),Dom.element('p','',tool.description),Dom.element('pre','agent-json',JSON.stringify(tool.inputSchema,null,2)));const input=Dom.element('textarea');input.rows=4;input.placeholder='JSON arguments';input.value='{}';input.setAttribute('aria-label','Arguments for '+tool.name);const result=Dom.element('pre','agent-json');card.append(input,Dom.button('Call tool',async()=>{try{const value=await this.actions.callTool(tool.name,JSON.parse(input.value));result.textContent=JSON.stringify(value,null,2).slice(0,24000);}catch(error){result.textContent=error.message;}}),result);this.toolList.append(card);}
  }
}
